In [1]:
import pandas as pd
pd.set_option('display.max_rows', None)  # 显示所有行
pd.set_option('display.max_columns', None)  # 显示所有列

In [3]:
file_path = 'convergence.csv'
df = pd.read_csv(file_path)

# df = df.drop(columns=['pbid'])
df = df[df['depth'] >= 20]
df = df[(df['num_params'] >= 1)]
grouped_df = df.groupby(['pkid', 'layers', 'method'], as_index=False).agg({
    "depth": 'mean',
    # 'culled_depth': 'mean',
    'num_params': 'mean',
})
# values = ["depth", "culled_depth"]
values = ["depth", 'num_params']

## 分组并把组作为索引
pivot_df = grouped_df.pivot(index =['pkid'], columns='method', values=values)

method_order = ['HeaSolver', 'PenaltySolver', 'ChocoSolver', 'QtoSimplifyDiscardSolver']
# method_order = ['QtoSolver', 'QtoSimplifySolver', 'QtoSimplifyDiscardSolver']
pivot_df = pivot_df.reindex(columns=pd.MultiIndex.from_product([values, method_order]))

pivot_df

         depth                                                    num_params  \
     HeaSolver PenaltySolver ChocoSolver QtoSimplifyDiscardSolver  HeaSolver
pkid
0       1441.0        1408.0      1511.0                   1381.1     3600.0


     PenaltySolver ChocoSolver QtoSimplifyDiscardSolver
pkid
0            100.0         8.0                     28.0

In [11]:
culled_depth_Qtosimplify_discard = pivot_df['depth']['QtoSimplifyDiscardSolver']
num_params_Qtosimplify_discard = pivot_df['num_params']['QtoSimplifyDiscardSolver']

# 计算新的列并将其添加到 `pivot_df`
pivot_df[('culled_depth_per_param', 'QtoSimplifyDiscardSolver')] = culled_depth_Qtosimplify_discard / num_params_Qtosimplify_discard
pivot_df

         depth                                                    num_params  \
     HeaSolver PenaltySolver ChocoSolver QtoSimplifyDiscardSolver  HeaSolver
pkid
0         46.0         87.00      507.00               102.000000       90.0
1         91.0        148.00     1888.00              1296.200000      225.0
2        121.0        174.00     2688.00              3091.520000      315.0
3        156.0        207.00     3848.00              3753.580000      420.0
4         76.0        259.08     1878.65               454.400000      180.0
5         91.0        309.90     1696.65               365.100000      225.0
6        116.0        744.72     3207.48              1016.260000      300.0
7        136.0        790.62     3515.32               986.380000      360.0
8         56.0        174.51     1323.64               343.520000      120.0
9         91.0        249.94     3532.82               698.000000      225.0
10       106.0        284.84     4395.55              2897.360000      270.0
11       121.0        324.31     5275.26              3336.710000      315.0
12        51.0        110.00     1082.00               225.830000      105.0
13        66.0        136.03     2039.00               455.630000      150.0
14        86.0        169.50     3137.00              1437.740000      210.0
15       106.0        194.18     4562.00              2011.490000      270.0
16        61.0        220.07     1078.91               312.563830      135.0
17        76.0        283.30     1345.86               581.757576      180.0
18        96.0        390.24     1969.26              1192.731959      240.0
19       116.0        480.80     2535.26              2250.134021      300.0

                                                         \
     PenaltySolver ChocoSolver QtoSimplifyDiscardSolver
pkid
0             10.0        10.0                 3.000000
1             10.0        10.0                26.270000
2             10.0        10.0                53.210000
3             10.0        10.0                65.160000
4             10.0        10.0                 8.440000
5             10.0        10.0                 5.680000
6             10.0        10.0                25.500000
7             10.0        10.0                17.690000
8             10.0        10.0                 4.030000
9             10.0        10.0                 8.000000
10            10.0        10.0                33.280000
11            10.0        10.0                38.330000
12            10.0        10.0                 4.040000
13            10.0        10.0                 6.560000
14            10.0        10.0                21.860000
15            10.0        10.0                28.090000
16            10.0        10.0                10.946809
17            10.0        10.0                21.848485
18            10.0        10.0                49.082474
19            10.0        10.0               100.237113

       culled_depth_per_param
     QtoSimplifyDiscardSolver
pkid
0                   34.000000
1                   49.341454
2                   58.100357
3                   57.605586
4                   53.838863
5                   64.278169
6                   39.853333
7                   55.759186
8                   85.240695
9                   87.250000
10                  87.060096
11                  87.052178
12                  55.898515
13                  69.455793
14                  65.770357
15                  71.608758
16                  28.552964
17                  26.626907
18                  24.300567
19                  22.448113

In [12]:
mean_values_per_column = pivot_df.mean()
print(mean_values_per_column)

depth                   HeaSolver                     93.250000
                        PenaltySolver                286.902000
                        ChocoSolver                 2575.283000
                        QtoSimplifyDiscardSolver    1340.445369
num_params              HeaSolver                    231.750000
                        PenaltySolver                 10.000000
                        ChocoSolver                   10.000000
                        QtoSimplifyDiscardSolver      26.562744
culled_depth_per_param  QtoSimplifyDiscardSolver      56.202095
dtype: float64

In [13]:
# 定义格式化函数
import numpy as np
# def format_value(val):
#     if np.isnan(val):  # 如果是NaN值则返回空字符
#         return "NaN"
#     elif val < 100:  # 如果值小于100，保留3位有效数字
#         return f"{val:.2f}"
#     else:  # 如果值大于等于100，不保留小数点
#         return f"{val:.0f}"

# 按行遍历输出，每个值用 & 分隔
for row in pivot_df.itertuples(index=False):
    formatted_row = [f"{x:5.0f}" for x in row]
    print(" & ".join(formatted_row))

   46 &    87 &   507 &   102 &    90 &    10 &    10 &     3 &    34
   91 &   148 &  1888 &  1296 &   225 &    10 &    10 &    26 &    49
  121 &   174 &  2688 &  3092 &   315 &    10 &    10 &    53 &    58
  156 &   207 &  3848 &  3754 &   420 &    10 &    10 &    65 &    58
   76 &   259 &  1879 &   454 &   180 &    10 &    10 &     8 &    54
   91 &   310 &  1697 &   365 &   225 &    10 &    10 &     6 &    64
  116 &   745 &  3207 &  1016 &   300 &    10 &    10 &    26 &    40
  136 &   791 &  3515 &   986 &   360 &    10 &    10 &    18 &    56
   56 &   175 &  1324 &   344 &   120 &    10 &    10 &     4 &    85
   91 &   250 &  3533 &   698 &   225 &    10 &    10 &     8 &    87
  106 &   285 &  4396 &  2897 &   270 &    10 &    10 &    33 &    87
  121 &   324 &  5275 &  3337 &   315 &    10 &    10 &    38 &    87
   51 &   110 &  1082 &   226 &   105 &    10 &    10 &     4 &    56
   66 &   136 &  2039 &   456 &   150 &    10 &    10 &     7 &    69
   86 &   170 &  3137 &  1438 &   210 &    10 &    10 &    22 &    66
  106 &   194 &  4562 &  2011 &   270 &    10 &    10 &    28 &    72
   61 &   220 &  1079 &   313 &   135 &    10 &    10 &    11 &    29
   76 &   283 &  1346 &   582 &   180 &    10 &    10 &    22 &    27
   96 &   390 &  1969 &  1193 &   240 &    10 &    10 &    49 &    24
  116 &   481 &  2535 &  2250 &   300 &    10 &    10 &   100 &    22

In [14]:
# 选取 'depth' 下的所有列，并剔除 'NewSolver' 和 'QtoSimplifySolver'
depth_df = pivot_df['depth'].drop(columns=['NewSolver', 'QtoSimplifySolver'], errors='ignore')

# 选取 'culled_depth_per_param' 下的 'QtoSimplifyDiscardSolver' 列
Qtosimplify_discard_df = pivot_df['culled_depth_per_param'][['QtoSimplifyDiscardSolver']]

# 合并处理后的 'depth' 列与 'QtoSimplifyDiscardSolver' 列，并指定后缀避免冲突
culled_depth_df = depth_df.join(Qtosimplify_discard_df, lsuffix='_depth', rsuffix='_culled')

# 按行遍历输出值，每个值用 & 分隔
for row in culled_depth_df.itertuples(index=False):
    formatted_row = [f"{x:5.0f}" for x in row]
    print(" & ".join(formatted_row))

   46 &    87 &   507 &   102 &    34
   91 &   148 &  1888 &  1296 &    49
  121 &   174 &  2688 &  3092 &    58
  156 &   207 &  3848 &  3754 &    58
   76 &   259 &  1879 &   454 &    54
   91 &   310 &  1697 &   365 &    64
  116 &   745 &  3207 &  1016 &    40
  136 &   791 &  3515 &   986 &    56
   56 &   175 &  1324 &   344 &    85
   91 &   250 &  3533 &   698 &    87
  106 &   285 &  4396 &  2897 &    87
  121 &   324 &  5275 &  3337 &    87
   51 &   110 &  1082 &   226 &    56
   66 &   136 &  2039 &   456 &    69
   86 &   170 &  3137 &  1438 &    66
  106 &   194 &  4562 &  2011 &    72
   61 &   220 &  1079 &   313 &    29
   76 &   283 &  1346 &   582 &    27
   96 &   390 &  1969 &  1193 &    24
  116 &   481 &  2535 &  2250 &    22

In [15]:
# 选取所需的列
depth_Qto_discard = pivot_df['depth']['QtoSimplifyDiscardSolver']
depth_choco = pivot_df['depth']['ChocoSolver']
culled_depth_Qto_discard = pivot_df['culled_depth_per_param']['QtoSimplifyDiscardSolver']
# 方法1：每行相除取平均
# depth 下 ChocoSolver / QtoSimplifyDiscardSolver 的倍数
row_wise_ratio_depth_choco_Qto_discard = (depth_choco / depth_Qto_discard).mean()

# culled_depth_per_param 下 ChocoSolver / QtoSimplifyDiscardSolver 的倍数
row_wise_ratio_culled_depth_choco_Qto_discard = (depth_choco / culled_depth_Qto_discard).mean()

# 方法2：整列取平均后相除
# depth 下 ChocoSolver / QtoSimplifyDiscardSolver 的整列平均的倍数
col_avg_ratio_depth_choco_Qto_discard = depth_choco.mean() / depth_Qto_discard.mean()

# culled_depth_per_param 下 ChocoSolver / QtoSimplifyDiscardSolver 的整列平均的倍数
col_avg_ratio_culled_depth_choco_Qto_discard = depth_choco.mean() / culled_depth_Qto_discard.mean()

# 输出结果
print(f"每行相除取平均 - depth 下 ChocoSolver / QtoSimplifyDiscardSolver 的倍数: {row_wise_ratio_depth_choco_Qto_discard:.2f}")
# print(f"每行相除取平均 - depth 下 ChocoSolver / culled_depth_per_param 下 QtoSimplifyDiscardSolver 的倍数: {row_wise_ratio_culled_depth_choco_Qto_discard:.2f}")
print(f"整列取平均后相除 - depth 下 ChocoSolver / QtoSimplifyDiscardSolver 的倍数: {col_avg_ratio_depth_choco_Qto_discard:.2f}")
# print(f"整列取平均后相除 - depth 下 ChocoSolver / culled_depth_per_param 下 QtoSimplifyDiscardSolver 的倍数: {col_avg_ratio_culled_depth_choco_Qto_discard:.2f}")

每行相除取平均 - depth 下 ChocoSolver / QtoSimplifyDiscardSolver 的倍数: 2.90
整列取平均后相除 - depth 下 ChocoSolver / QtoSimplifyDiscardSolver 的倍数: 1.92

In [16]:
# 选择 `culled_depth` 和 `num_params` 中的 `QtoSimplifyDiscardSolver` 列

# 查看结果
pivot_df

         depth                                                    num_params  \
     HeaSolver PenaltySolver ChocoSolver QtoSimplifyDiscardSolver  HeaSolver
pkid
0         46.0         87.00      507.00               102.000000       90.0
1         91.0        148.00     1888.00              1296.200000      225.0
2        121.0        174.00     2688.00              3091.520000      315.0
3        156.0        207.00     3848.00              3753.580000      420.0
4         76.0        259.08     1878.65               454.400000      180.0
5         91.0        309.90     1696.65               365.100000      225.0
6        116.0        744.72     3207.48              1016.260000      300.0
7        136.0        790.62     3515.32               986.380000      360.0
8         56.0        174.51     1323.64               343.520000      120.0
9         91.0        249.94     3532.82               698.000000      225.0
10       106.0        284.84     4395.55              2897.360000      270.0
11       121.0        324.31     5275.26              3336.710000      315.0
12        51.0        110.00     1082.00               225.830000      105.0
13        66.0        136.03     2039.00               455.630000      150.0
14        86.0        169.50     3137.00              1437.740000      210.0
15       106.0        194.18     4562.00              2011.490000      270.0
16        61.0        220.07     1078.91               312.563830      135.0
17        76.0        283.30     1345.86               581.757576      180.0
18        96.0        390.24     1969.26              1192.731959      240.0
19       116.0        480.80     2535.26              2250.134021      300.0

                                                         \
     PenaltySolver ChocoSolver QtoSimplifyDiscardSolver
pkid
0             10.0        10.0                 3.000000
1             10.0        10.0                26.270000
2             10.0        10.0                53.210000
3             10.0        10.0                65.160000
4             10.0        10.0                 8.440000
5             10.0        10.0                 5.680000
6             10.0        10.0                25.500000
7             10.0        10.0                17.690000
8             10.0        10.0                 4.030000
9             10.0        10.0                 8.000000
10            10.0        10.0                33.280000
11            10.0        10.0                38.330000
12            10.0        10.0                 4.040000
13            10.0        10.0                 6.560000
14            10.0        10.0                21.860000
15            10.0        10.0                28.090000
16            10.0        10.0                10.946809
17            10.0        10.0                21.848485
18            10.0        10.0                49.082474
19            10.0        10.0               100.237113

       culled_depth_per_param
     QtoSimplifyDiscardSolver
pkid
0                   34.000000
1                   49.341454
2                   58.100357
3                   57.605586
4                   53.838863
5                   64.278169
6                   39.853333
7                   55.759186
8                   85.240695
9                   87.250000
10                  87.060096
11                  87.052178
12                  55.898515
13                  69.455793
14                  65.770357
15                  71.608758
16                  28.552964
17                  26.626907
18                  24.300567
19                  22.448113